=== aradan04/ordinario-ftw/Datos/dtd/combates.dtd
<!ELEMENT historial (combate*)>
<!ELEMENT combate (rival, personaje_id, resultado, stocks, escenario)>
<!ATTLIST combate 
    id ID #REQUIRED
    jugador_id NMTOKEN #REQUIRED>
<!ELEMENT rival (#PCDATA)>
<!ELEMENT personaje_id (#PCDATA)>
<!ELEMENT resultado (#PCDATA)>
<!ELEMENT stocks (#PCDATA)>
<!ELEMENT escenario (#PCDATA)>

=== aradan04/ordinario-ftw/Datos/combates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE historial SYSTEM "dtd/combates.dtd">
<historial>

    <!-- MKLEO -->

    <combate id="C-1" jugador_id="SMASH-01">
        <rival>Fox</rival>
        <personaje_id>ID-28</personaje_id>
        <resultado>Victoria</resultado>
        <stocks>2</stocks>
        <escenario>Final Destination</escenario>
    </combate>

    <combate id="C-2" jugador_id="SMASH-01">
        <rival>Sonic</rival>
        <personaje_id>ID-28</personaje_id>
        <resultado>Derrota</resultado>
        <stocks>0</stocks>
        <escenario>Smashville</escenario>
    </combate>

    <combate id="C-3" jugador_id="SMASH-01">
        <rival>Kazuya</rival>
        <personaje_id>ID-65</personaje_id>
        <resultado>Victoria</resultado>
        <stocks>1</stocks>
        <escenario>Battlefield</escenario>
    </combate>

    <combate id="C-4" jugador_id="SMASH-01">
        <rival>Snake</rival>
        <personaje_id>ID-28</personaje_id>
        <resultado>Victoria</resultado>
        <stocks>2</stocks>
        <escenario>Town and City</escenario>
    </combate>

    <combate id="C-5" jugador_id="SMASH-01">
        <rival>Palutena</rival>
        <personaje_id>ID-28</personaje_id>
        <resultado>Victoria</resultado>
        <stocks>3</stocks>
        <escenario>Battlefield</escenario>
    </combate>

    <combate id="C-6" jugador_id="SMASH-01">
        <rival>Steve</rival>
        <personaje_id>ID-65</personaje_id>
        <resultado>Derrota</resultado>
        <stocks>0</stocks>
        <escenario>Pokémon Stadium 2</escenario>
    </combate>

    <combate id="C-7" jugador_id="SMASH-01">
        <rival>Cloud</rival>
        <personaje_id>ID-28</personaje_id>
        <resultado>Victoria</resultado>
        <stocks>1</stocks>
        <escenario>Final Destination</escenario>
    </combate>

    <!-- SPARG0 -->

    <combate id="C-8" jugador_id="SMASH-02">
        <rival>Joker</rival>
        <personaje_id>ID-74</personaje_id>
        <resultado>Victoria</resultado>
        <stocks>3</stocks>
        <escenario>Smashville</escenario>
    </combate>

    <combate id="C-9" jugador_id="SMASH-02">
        <rival>Mario</rival>
        <personaje_id>ID-74</personaje_id>
        <resultado>Victoria</resultado>
        <stocks>2</stocks>
        <escenario>Battlefield</escenario>
    </combate>

    <combate id="C-10" jugador_id="SMASH-02">
        <rival>Roy</rival>
        <personaje_id>ID-74</personaje_id>
        <resultado>Victoria</resultado>
        <stocks>1</stocks>
        <escenario>Town and City</escenario>
    </combate>

    <combate id="C-11" jugador_id="SMASH-02">
        <rival>Snake</rival>
        <personaje_id>ID-74</personaje_id>
        <resultado>Derrota</resultado>
        <stocks>0</stocks>
        <escenario>Kalos</escenario>
    </combate>

    <combate id="C-12" jugador_id="SMASH-02">
        <rival>Samus</rival>
        <personaje_id>ID-74</personaje_id>
        <resultado>Victoria</resultado>
        <stocks>2</stocks>
        <escenario>Final Destination</escenario>
    </combate>

    <combate id="C-13" jugador_id="SMASH-02">
        <rival>Steve</rival>
        <personaje_id>ID-74</personaje_id>
        <resultado>Derrota</resultado>
        <stocks>0</stocks>
        <escenario>Pokémon Stadium 2</escenario>
    </combate>

    <combate id="C-14" jugador_id="SMASH-02">
        <rival>Fox</rival>
        <personaje_id>ID-74</personaje_id>
        <resultado>Victoria</resultado>
        <stocks>2</stocks>
        <escenario>Battlefield</escenario>
    </combate>

    <!-- ACOLA -->

    <combate id="C-15" jugador_id="SMASH-03">
        <rival>Cloud</rival>
        <personaje_id>ID-78</personaje_id>
        <resultado>Victoria</resultado>
        <stocks>2</stocks>
        <escenario>Pokémon Stadium 2</escenario>
    </combate>

    <combate id="C-16" jugador_id="SMASH-03">
        <rival>Joker</rival>
        <personaje_id>ID-78</personaje_id>
        <resultado>Victoria</resultado>
        <stocks>1</stocks>
        <escenario>Battlefield</escenario>
    </combate>

    <combate id="C-17" jugador_id="SMASH-03">
        <rival>Pyra/Mythra</rival>
        <personaje_id>ID-78</personaje_id>
        <resultado>Victoria</resultado>
        <stocks>3</stocks>
        <escenario>Small Battlefield</escenario>
    </combate>

    <combate id="C-18" jugador_id="SMASH-03">
        <rival>Snake</rival>
        <personaje_id>ID-78</personaje_id>
        <resultado>Victoria</resultado>
        <stocks>2</stocks>
        <escenario>Kalos</escenario>
    </combate>

    <combate id="C-19" jugador_id="SMASH-03">
        <rival>Mario</rival>
        <personaje_id>ID-78</personaje_id>
        <resultado>Victoria</resultado>
        <stocks>2</stocks>
        <escenario>Smashville</escenario>
    </combate>

    <combate id="C-20" jugador_id="SMASH-03">
        <rival>Byleth</rival>
        <personaje_id>ID-78</personaje_id>
        <resultado>Derrota</resultado>
        <stocks>0</stocks>
        <escenario>Final Destination</escenario>
    </combate>

    <combate id="C-21" jugador_id="SMASH-03">
        <rival>Fox</rival>
        <personaje_id>ID-78</personaje_id>
        <resultado>Victoria</resultado>
        <stocks>2</stocks>
        <escenario>Battlefield</escenario>
    </combate>

</historial>
